project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 - Learning Diary (JTSE)"
  author: "James Tan"
  date: "01/01/2024"
  chapters:
      - index.qmd
      - Chapter 1.qmd
      - Chapter 2.qmd
      - Chapter 3.qmd
      - Chapter 4.qmd
      - Chapter 5.qmd
      - Chapter 6.qmd
      - Chapter 7.qmd
      - Chapter 8.qmd
      - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    always_allow_html: yes

editor: visual


